/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124032-gfcffc0e1c5-20260418"
#endif /* AVUTIL_FFVERSION_H */
